# Generated by Django 4.2.1 on 2023-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='hobby',
        ),
        migrations.AlterField(
            model_name='template',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='give_food',
            field=models.TextField(),
        ),
    ]
