# Generated by Django 4.2.1 on 2023-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0002_remove_template_hobby_alter_template_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_member',
            field=models.TextField(),
        ),
    ]
