# Generated by Django 4.2.1 on 2023-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0003_alter_room_current_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='talk_topic',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='leader',
            new_name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='age',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='give_food',
            field=models.TextField(default='돼지껍데기'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sex',
            field=models.CharField(default='남', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
