# Generated by Django 4.2.1 on 2023-05-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0004_article_comment_recomment'),
        ('ddjapp', '0005_room_request_member_request'),
    ]

    operations = [
    ]
