# Generated by Django 4.2.1 on 2023-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0006_merge_20230520_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='matched',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
