# Generated by Django 4.2.1 on 2023-05-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddjapp', '0007_room_matched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='room',
            name='request_member',
        ),
        migrations.AlterField(
            model_name='request',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to='ddjapp.room'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_member',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='want_member',
            field=models.IntegerField(),
        ),
    ]
