# Generated by Django 4.2.1 on 2023-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0008_remove_room_finished_remove_room_request_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='req_member',
            new_name='member',
        ),
        migrations.AddField(
            model_name='request',
            name='age',
            field=models.TextField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='sex',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='talk_topic',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
