# Generated by Django 4.2.1 on 2023-05-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0009_rename_req_member_request_member_request_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
