# Generated by Django 4.2.1 on 2023-05-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0009_rename_req_member_request_member_request_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddjapp.request')),
                ('roomLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddjapp.room')),
            ],
        ),
    ]
