# Generated by Django 4.2.1 on 2023-05-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0010_rename_reciever_request_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddjapp.request')),
                ('roomLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddjapp.room')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ddjapp.chatting'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
