# Generated by Django 4.2.1 on 2023-05-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddjapp', '0010_rename_reciever_request_receiver'),
        ('ddjapp', '0011_alter_comment_article_delete_article'),
    ]

    operations = [
    ]
